# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=64)),
                ('pwd_hash', models.CharField(max_length=64)),
                ('unique_token', models.CharField(max_length=128)),
                ('current_session', models.CharField(max_length=128)),
                ('created', models.DateTimeField(auto_now=True)),
                ('status', models.SmallIntegerField(choices=[(1, 'active'), (2, 'disabled'), (128, 'deleted')])),
            ],
        ),
        migrations.CreateModel(
            name='AccountPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32)),
                ('target_objects', models.SmallIntegerField(choices=[(1, 'active'), (2, 'disabled'), (128, 'deleted')])),
            ],
        ),
        migrations.CreateModel(
            name='AccountRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='permissions',
            field=models.ManyToManyField(to='api.AccountPermission'),
        ),
    ]
