# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 13:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountpermission',
            old_name='name',
            new_name='endpoint',
        ),
        migrations.RenameField(
            model_name='accountpermission',
            old_name='code',
            new_name='method',
        ),
        migrations.AddField(
            model_name='accountrole',
            name='name',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accountrole',
            name='permissions',
            field=models.ManyToManyField(to='api.AccountPermission'),
        ),
        migrations.AddField(
            model_name='accountrole',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'active'), (2, 'disabled'), (128, 'deleted')], default=1),
            preserve_default=False,
        ),
    ]
