# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-19 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171110_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='login',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
