# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-22 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180319_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='accountpermission',
            name='endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Endpoint'),
        ),
        migrations.AlterField(
            model_name='accountpermission',
            name='target_objects',
            field=models.SmallIntegerField(choices=[(1, 'own_objects'), (2, 'child_objects'), (128, 'all_objects')]),
        ),
    ]
