# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-04 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180322_0730'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpermission',
            name='target_objects',
        ),
        migrations.AddField(
            model_name='accountpermission',
            name='object_permission',
            field=models.SmallIntegerField(choices=[('own_objects', 'own_objects'), ('child_objects', 'child_objects'), ('all_objects', 'all_objects')], default=1),
            preserve_default=False,
        ),
    ]
