# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-20 03:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180404_0605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pwd_hash',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='accountpermission',
            name='object_permission',
            field=models.SmallIntegerField(choices=[(1, 'own_objects'), (2, 'child_objects'), (128, 'all_objects')]),
        ),
    ]
