# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-23 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.AccountRole'),
        ),
    ]
