# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-14 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_account_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='type',
            field=models.CharField(choices=[('recovery', 'Recovery'), ('authorization', 'Authorization')], default='authorization', max_length=24, verbose_name='Type'),
        ),
    ]
