# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-16 09:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_token_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABACAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ABACAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('attr_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ABACPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=128)),
                ('action', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ABACAction')),
            ],
        ),
        migrations.CreateModel(
            name='ABACResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=128)),
                ('comment', models.TextField()),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ABACRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], max_length=64)),
                ('rule', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='abacpolicy',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ABACResource'),
        ),
        migrations.AddField(
            model_name='abacattribute',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='api.ABACResource'),
        ),
        migrations.AddField(
            model_name='abacaction',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='api.ABACResource'),
        ),
    ]
