# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-16 17:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20180516_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='abacrule',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='api.ABACPolicy'),
        ),
        migrations.AlterField(
            model_name='abacrule',
            name='rule',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
