# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-03 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20180516_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpermission',
            name='endpoint',
        ),
        migrations.RemoveField(
            model_name='account',
            name='permissions',
        ),
        migrations.RemoveField(
            model_name='accountrole',
            name='permissions',
        ),
        migrations.AddField(
            model_name='account',
            name='cidr',
            field=models.CharField(default='0.0.0.0/0', max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('user', 'User'), ('service', 'Service')], default='user', max_length=12),
        ),
        migrations.DeleteModel(
            name='AccountPermission',
        ),
        migrations.DeleteModel(
            name='Endpoint',
        ),
    ]
