# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-17 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180705_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountrole',
            name='text_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
