# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-27 11:24
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20180705_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='abacrule',
            name='mask',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), null=True, size=None),
        ),
    ] if settings.DATABASES['default']['ENGINE'] in ('pgsql', 'postgres', 'postgre') else []
