# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-17 06:35
from __future__ import unicode_literals

from django.db import migrations


def migrate_ids(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    AccountRole = apps.get_model('api', 'AccountRole')
    for account_role in AccountRole.objects.all():
        account_role.text_id = str(account_role.id)
        account_role.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0014_accountrole_text_id'),
    ]

    operations = [
        migrations.RunPython(migrate_ids, reverse_code=lambda x, y: ""),
    ]
