# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-08-21 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

def make_domains(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    DomainModel = apps.get_model('api', 'ABACDomain')
    ResourceModel = apps.get_model('api', 'abacresource')
    for resource in ResourceModel.objects.all():
        DomainModel.objects.get_or_create(id=resource.domain)


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_abacrule_mask'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABACDomain',
            fields=[
                ('id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('default_result', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], null=True, max_length=64)),
            ],
        ),
        migrations.RunPython(make_domains, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='abacresource',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='domain', to='api.ABACDomain'),
        ),
    ]
