# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-17 06:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0015_migrate_role_numeric_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountrole',
            name='id'
        ),
        migrations.RenameField(
            model_name='accountrole',
            old_name='text_id',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='accountrole',
            name="id",
            field=models.CharField(max_length=255, primary_key=True)
        ),
    ]
