# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-09-28 17:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import jsonfield.fields
from django.db.migrations import RunPython


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20190821_1419'),
    ]


    operations = [
        migrations.RemoveField(
            model_name='abacrule',
            name='mask',
        ) if settings.DATABASES['default']['ENGINE'] in ('pgsql', 'postgres', 'postgre') else RunPython(RunPython.noop),
        migrations.AddField(
            model_name='abacrule',
            name='mask',
            field=models.ManyToManyField(to='api.ABACAttribute'),
        ),
        migrations.AlterField(
            model_name='abacrule',
            name='rule',
            field=jsonfield.fields.JSONField(),
        ),
    ]
