# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-29 12:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_text_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='type',
            field=models.CharField(choices=[('recovery', 'Recovery'), ('authorization', 'Authorization'), ('2_fa_intermediate', '2fa intermediate'), ('2_fa_verification', 'Second factor verification')], default='authorization', max_length=24, verbose_name='Type'),
        ),
    ]
