# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-10-25 15:56
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20190928_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_data',
            field=jsonfield.fields.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_id',
            field=models.IntegerField(null=True),
        ),
    ]
