# Generated by Django 2.2.6 on 2020-04-23 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200420_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='abacaction',
            old_name='creator',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='abacattribute',
            old_name='creator',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='abacdomain',
            old_name='creator',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='abacpolicy',
            old_name='creator',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='abacresource',
            old_name='creator',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='abacrule',
            old_name='creator',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='creator',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='accountrole',
            old_name='creator',
            new_name='owner',
        ),
    ]