# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-17 06:42
from __future__ import unicode_literals

from django.db import migrations, models


def migrate_ids(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    AccountRole = apps.get_model('api', 'AccountRole')
    for account_role in AccountRole.objects.all():
        account_role.id = str(account_role.name)
        account_role.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0022_auto_20200706_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountrole',
            name="id",
            field=models.CharField(max_length=255, primary_key=True)
        ),
        migrations.RunPython(migrate_ids),
    ]

