# Generated by Django 2.2.6 on 2022-11-16 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210212_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='type',
            field=models.CharField(choices=[('recovery', 'Recovery'), ('authorization', 'Authorization'), ('activation', 'Activation'), ('deletion', 'Deletion')], default='authorization', max_length=24, verbose_name='Type'),
        ),
    ]
