# Generated by Django 2.2.6 on 2021-05-26 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20210212_1157'),
        ('api', '0023_auto_20201026_0754'),
    ]

    operations = [
    ]
