version: "2"

services:
  authorization:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}.authorization
    environment:
      DJANGO_CONFIGURATION: Production
    networks:
      - ${COMPOSE_PROJECT_NAME}-network

  authorization_postgres:
    image: postgres:9.5
    container_name: ${COMPOSE_PROJECT_NAME}.authorization.postgres
    environment: 
      CONTAINER_NAME: ${COMPOSE_PROJECT_NAME}.authorization.postgres
    volumes:
      - ./postgres/${CONTAINER_NAME}/data:/var/lib/postgresql/data
      - ./postgres/${CONTAINER_NAME}/conf:/etc/postgresql
      - ./postgres/${CONTAINER_NAME}/logs:/var/log/postgresql
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: authorization
      POSTGRES_USER: authorization
      POSTGRES_PASSWORD: authorization

    networks:
      - ${COMPOSE_PROJECT_NAME}-network