version: "2"

services:
  authorization:
    build:
      context: ../
      dockerfile: deployment/Dockerfile
    container_name: authorization
    environment:
      DJANGO_CONFIGURATION: Production
    networks:
      - test-network

  authorization_postgres:
    image: postgres:9.5
    container_name: postgres.authorization
    volumes:
      - ./postgres/${CONTAINER_NAME}/data:/var/lib/postgresql/data
      - ./postgres/${CONTAINER_NAME}/conf:/etc/postgresql
      - ./postgres/${CONTAINER_NAME}/logs:/var/log/postgresql
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_DB: authorization
      POSTGRES_USER: authorization
      POSTGRES_PASSWORD: authorization

    networks:
      - test-network

networks:
  test-network:
    driver: bridge