# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-29 12:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0017_auto_20180829_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecondAuthFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[('PHONE', 'Phone')])),
                ('factor_id', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_auth_factors', to='api.Account')),
            ],
        ),
    ]
