# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-30 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20180829_1246'),
        ('two_factor_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('second_auth_factor_id', models.CharField(max_length=255)),
                ('expire', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Account')),
            ],
        ),
    ]
