# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-30 08:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_auth', '0002_intermediatetoken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intermediatetoken',
            old_name='second_auth_factor_id',
            new_name='second_factor_id',
        ),
    ]
