# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-30 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_auth', '0004_auto_20180830_0905'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intermediatetoken',
            old_name='second_factor_id',
            new_name='factor_id',
        ),
        migrations.AddField(
            model_name='intermediatetoken',
            name='factor_type',
            field=models.CharField(choices=[('PHONE', 'Phone')], default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intermediatetoken',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
