# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-31 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two_factor_auth', '0005_auto_20180830_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='intermediatetoken',
            name='verification_type',
            field=models.IntegerField(choices=[(1, 'Binding'), (2, 'Authorization')], default=1),
            preserve_default=False,
        ),
    ]
