# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-08-31 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20180831_0727'),
        ('two_factor_auth', '0006_intermediatetoken_verification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthFactor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SMS', 'SMS')], max_length=255)),
                ('factor_id', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_factors', to='api.Account')),
            ],
        ),
        migrations.RemoveField(
            model_name='secondauthfactor',
            name='account',
        ),
        migrations.AlterField(
            model_name='intermediatetoken',
            name='factor_type',
            field=models.CharField(choices=[('SMS', 'SMS')], max_length=255),
        ),
        migrations.DeleteModel(
            name='SecondAuthFactor',
        ),
    ]
